services:
    api-gateway:
        build: ./api-gateway
        ports: ["8081:8081"]
        networks:
            - default
        depends_on:
            - payment-service
            - orders-service

    payment-service:
        build: ./payment-service
        ports: ["8082:8082"]
        networks:
            - default
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/storage
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        depends_on:
            - postgres
            - kafka

    orders-service:
        build: ./orders-service
        ports: [ "8083:8083" ]
        networks:
            - default
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/storage
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        depends_on:
            - postgres
            - kafka

    zookeeper:
        image: confluentinc/cp-zookeeper:7.5.0
        hostname: zookeeper
        ports: ["2181:2181"]
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - default

    kafka:
        image: confluentinc/cp-kafka:7.5.0
        hostname: kafka
        ports: [ "9092:9092", "9094:9094"]
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_NUM_PARTITIONS: 1
        depends_on:
            - zookeeper
        networks:
            - default


    postgres:
        image: postgres:14
        environment:
            POSTGRES_DB: storage
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - default