services:
  api-gateway:
    build: ./api-gateway
    ports: ["8081:8081"]
    networks:
      - default
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default
