services:
    api-gateway:
        build: ./api-gateway
        ports: ["8081:8081"]
        networks:
            - default

    payment-service:
        build: ./payment-service
        ports: ["8082:8082"]
        networks:
            - default

    orders-service:
        build: ./orders-service
        ports: [ "8083:8083" ]
        networks:
            - default

    postgres:
        image: postgres:14
        environment:
            POSTGRES_DB: storage
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - default
